# crpush — recipes. `just ci` is the pre-push gate.

default:
    @just --list

# one-time per clone: wire up the pre-push hook that enforces `just ci`
install-hooks:
    git config core.hooksPath .githooks
    @echo "pre-push hook installed — 'just ci' now runs automatically before every push"

# pre-push gate: typecheck + unit tests — don't push without this green
ci: typecheck test

# tsc --noEmit, failing only on errors outside node_modules
# (vitest/workers-types lib conflicts in node_modules are known noise)
typecheck:
    #!/usr/bin/env bash
    set -uo pipefail
    errors=$(npx tsc --noEmit 2>&1 | grep 'error TS' | grep -v '^node_modules/' || true)
    if [ -n "$errors" ]; then
        echo "$errors"
        exit 1
    fi
    echo "typecheck clean"

test:
    npm test

# integration tests (workers pool, slower — not part of `ci`... run before deploy)
test-integration:
    npm run test:integration

dev:
    npm run dev

# regenerate src/worker/styles.ts (compiled Tailwind) after changing UI classes
css:
    #!/usr/bin/env bash
    set -euo pipefail
    tmp=$(mktemp -d)
    printf '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n' > "$tmp/in.css"
    npx tailwindcss@3.4.17 -i "$tmp/in.css" -o "$tmp/out.css" --content "src/worker/index.ts,src/worker/templates.ts" --minify
    node -e "const fs=require('fs');const css=fs.readFileSync('$tmp/out.css','utf8');fs.writeFileSync('src/worker/styles.ts','// Generated by \`just css\` — do not edit by hand.\n// Compiled Tailwind v3 subset covering the classes used in src/worker/*.ts.\nexport const STYLES: string = '+JSON.stringify(css)+';\n')"
    rm -rf "$tmp"
    echo "src/worker/styles.ts regenerated"

# generate a new D1 migration from src/worker/schema.ts changes
db-generate name:
    npx drizzle-kit generate --name {{name}}

# apply pending migrations to the production D1 database
db-migrate:
    npx wrangler d1 migrations apply crpush --remote

# deploy to Cloudflare, gated on ci + integration tests
deploy: ci test-integration
    npm run deploy
